apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: banga-redis
spec:
  replicas: 1
  serviceName: banga-redis
  selector:
    matchLabels:
      app: banga-redis
  template:
    metadata:
      labels:
        app: banga-redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

