apiVersion: apps/v1
kind: Deployment
metadata:
  name: banga-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banga-ui
  template:
    metadata:
      labels:
        app: banga-ui
    spec:
      containers:
      - name: banga-ui
        image: devopseasylearning/banga-ui:v0.0.1
        ports:
        - containerPort: 3000
        env:
        - name: AUTH_HOST
          value: auth
        - name: AUTH_PORT
          value: "8080"
        - name: WEATHER_HOST
          value: weather
        - name: WEATHER_PORT
          value: "5000"
        - name: REDIS_USER
          value: redis
        - name: REDIS_PASSWORD
          value: redis

